# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scripting Secures Success
name: Matt Bobke
email: matt@mattbobke.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about my love for all things automation and administration
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattbobke.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: mcbobke/mcbobke.github.io
logo: "/images/IMG_0398.jpeg"
twitter_username: mattbobke
github_username: mcbobke
author:
  name: "Matt Bobke"
  avatar: "/images/IMG_0398.jpeg"
  location: "Aliso Viejo, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/mcbobke"
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/mattbobke"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/mcbobke"
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/mattbobke"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-139643387-1"
    anonymize_ip: false
repository: "mcbobke/mcbobke.github.io"
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "dark"
locale: "en-US"
search: true
plugins:
  - jekyll-feed
  - jekyll-include-cache
include: ["_pages","_posts"]
paginate: 10 # amount of posts to show
paginate_path: /blog/page:num/
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      toc: true
      toc_label: "Navigate this Post"
      toc_icon: "fas fa-search"
      layout: single
      classes: wide
      author_profile: true
      share: true
      comments: true
  - scope:
      path: "_pages"
      type: pages
    values:
      toc: true
      toc_label: "Navigate this Page"
      toc_icon: "fas fa-search"
      layout: single
      comments: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/